function nome()
    print('Hello World!')
end

print(nome) -- NÃO ESTÁ CHAMANDO A FUNÇÃO E SIM IMPRIMINDO A FUNÇÃO, ASSIM GERANDO O LOCAL DO ARMAZENAMENTO DOS DADOS DA FUNÇÃO.
nome() -- ESTAMOS CHAMNDO A FUNÇÃO, ASSIM EXECUTANDO SEU CONTEUDO.