print(10<10) -- false (10 não é menor que 10)
print(10>10) -- false (10 não é maior que 10)
print(10<=10) -- true (10 é menor ou igual a 10)
print(10>=10) -- true (10 é maior ou igual a 10)
print(10==10) -- true (10 é igual a 10)
print(10~=10) -- false (10 não é diferente de 10)
print('Olá!'=='Olá!') -- true (As strings são idênticas)
print('olá!'=='Olá!') -- false (Lua diferencia maiúsculas e minúsculas)
print('Olá!'~='Olá!') -- false (As strings são idênticas, então não são diferentes)